name: pixel_demolition_tycoon
description: A `coodoo style` Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # http via dio
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.8.1

  # riverpod
  flutter_riverpod: ^2.3.9
  riverpod_annotation: ^2.1.3
  freezed_annotation: ^2.4.1

  # config
  envied: ^0.3.0+3

  # logging
  logging: ^1.2.0
  logging_appenders: ^1.2.0+1

  # Utils
  collection: ^1.17.2
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.12
  permission_handler: ^10.4.3
  device_info_plus: ^9.0.3
  connectivity_plus: ^4.0.2

  # Widgets
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7

  # Flame
  flame: ^1.10.0
  flame_audio: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.0
  json_serializable: ^6.7.1
  envied_generator: ^0.3.0+3
  custom_lint: ^0.5.2
  riverpod_lint: ^2.0.2
  freezed: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/audio/
